export const RETRIEVE_PUBLIC_USERS = "RETRIEVE_PUBLIC_USERS";

export const SEND_MESSAGE = "SEND_MESSAGE";

export const RETRIEVE_USER = "RETRIEVE_USER";
export const USER_SET_IS_ADMIN = "USER_SET_IS_ADMIN";
export const USER_UPDATE_PUBLIC_NAME = "USER_UPDATE_PUBLIC_NAME";
export const DELETE_USER = "DELETE_USER";
